messageConfig:
    root_route:
      topic: ism_general
      manage_topic: ism_general_manage
      subscription: ism_general_subscription
      service_url: pulsar://localhost:6650

    topic_routes:
      - selector: state/router
        topic: ism_state_router
        subscription: ism_state_router_subscription
        service_url: pulsar://localhost:6650

