name: alethic-ism-state-router
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - python-dotenv
  - psycopg2
  - pyyaml
  - pydantic
  - tenacity
  - pulsar-client
  - alethic-ism-core
  - alethic-ism-db
