name: alethic-ism-state-sync-store
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - python-dotenv
  - psycopg2
  - pyyaml
  - pydantic
  - tenacity
  - pulsar-client
  - restrictedpython
  - alethic-ism-core
  - alethic-ism-db
