apiVersion: v1
kind: Secret
metadata:
  name: alethic-ism-state-sync-store-secret
  namespace: alethic
stringData:
#  ROUTING_FILE: "/app/config/routing.yaml/routing.yaml"
  LOG_LEVEL: "DEBUG"
  DATABASE_URL: "postgresql://ism_db_user:ism_db_user@alethic-db-service:5432/ism_db"
  MSG_URL: "pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650"
  MSG_TOPIC: "ism_state_sync_store"
  MSG_MANAGE_TOPIC: ""
  MSG_TOPIC_SUBSCRIPTION: "ism_state_sync_store_subscription"
  .routing.yaml: |
    messageConfig:
        root_route:
          topic: ism_general
          manage_topic: ism_general_manage
          subscription: ism_general_subscription
          service_url: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650
    
        topic_routes:
          - selector: state/router
            topic: ism_state_router
            subscription: ism_state_router_subscription
            service_url: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650
    
